name: Run notebooks

on: [push, pull_request]

jobs:
  notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libosmesa6-dev

      - name: Install deps
        run: uv sync --python 3.12

      - name: Execute notebooks
        run: |
          find tutorials/ -name '*.ipynb' -execdir sed -i \
            's/pv\.set_jupyter_backend.*/pv.set_jupyter_backend(\\"none\\")\\n",\n"pv.OFF_SCREEN = True"/' \{} \;
          find tutorials/ -name '*.ipynb' ! -name '*_exercise.ipynb' | xargs uv run jupyter execute
