name: Run notebooks

on: [push, pull_request]

jobs:
  notebooks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install deps
        run: uv sync --python 3.12

      - name: Execute notebooks
        run: |
          uv run python -m nbclient --execute tutorials/*/*.ipynb
